#!/usr/bin/env bash
# This script prints numbers 1 to 20 and shows specific bad luck messages using a case statement

count=1

while [ $count -le 20 ]
do
    echo "$count"

    case $count in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac

    count=$((count + 1))
done
